version: '3.7'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "10m"

services:

  home:
    <<: *default-opts
    image: abiosoft/caddy:1.0.3-no-stats
    networks:
      - ntw_front
    volumes:
      - /root/docker-stack-this/traefik_stack6/webapps/home:/srv/home
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constraints: [node.role==manager]
      restart_policy:
        condition: any
        max_attempts: 10
      resources:
        limits:
          cpus: '0.20'
          memory: 32M
        reservations:
          cpus: '0.20'
          memory: 8M
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=PathPrefix(`/home`)"
      - "traefik.http.routers.home.entrypoints=web"
      - "traefik.http.services.home.loadbalancer.server.port=2015"

  blue:
    <<: *default-opts
    image: abiosoft/caddy:1.0.2-no-stats
    networks:
      - ntw_front
    volumes:
      - /root/docker-stack-this/traefik_stack6/webapps/blue:/srv/blue
    deploy:
      mode: replicated
      replicas: 3
      #placement:
      #  constraints: [node.role==manager]
      restart_policy:
        condition: any
        max_attempts: 10
      resources:
        limits:
          cpus: '0.20'
          memory: 32M
        reservations:
          cpus: '0.20'
          memory: 8M
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blue.rule=PathPrefix(`/blue`)"
      - "traefik.http.routers.blue.entrypoints=web"
      - "traefik.http.services.blue.loadbalancer.server.port=2015"

  green:
    <<: *default-opts
    image: abiosoft/caddy:1.0.1-no-stats
    networks:
      - ntw_front
    volumes:
      - /root/docker-stack-this/traefik_stack6/webapps/green:/srv/green
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constraints: [node.role==manager]
      restart_policy:
        condition: any
        max_attempts: 10
      resources:
        limits:
          cpus: '0.20'
          memory: 32M
        reservations:
          cpus: '0.20'
          memory: 8M
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.green.rule=PathPrefix(`/green`)"
      - "traefik.http.routers.green.entrypoints=web"
      - "traefik.http.services.green.loadbalancer.server.port=2015"

  whoami-a:
    <<: *default-opts
    image: containous/whoami:v1.4.0
    networks:
      - ntw_front
    deploy:
      mode: replicated
      replicas: 3
      #placement:
      #  constraints: [node.role==manager]
      restart_policy:
        condition: any
        max_attempts: 10
      resources:
        limits:
          cpus: '0.20'
          memory: 16M
        reservations:
          cpus: '0.05'
          memory: 4M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami-a.rule=PathPrefix(`/whoami-a`)"
        - "traefik.http.routers.whoami-a.entrypoints=web"
        - "traefik.http.services.whoami-a.loadbalancer.server.port=80"

  whoami-b:
    <<: *default-opts
    image: containous/whoami:v1.2.0
    networks:
      - ntw_front
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constraints: [node.role==manager]
      restart_policy:
        condition: any
        max_attempts: 10
      resources:
        limits:
          cpus: '0.20'
          memory: 16M
        reservations:
          cpus: '0.05'
          memory: 4M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami-b.rule=PathPrefix(`/whoami-b`)"
        - "traefik.http.routers.whoami-b.entrypoints=web"
        - "traefik.http.services.whoami-b.loadbalancer.server.port=80"

networks:
  ntw_front:
    external: true

