#!/bin/sh

# If needed, add permission to make this file executable | chmod +x start

echo; echo "Remove stacks ..."
docker stack rm proxy
docker stack rm webapp
sleep 2

echo; echo "Remove network ..."
docker network rm ntw_front
sleep 2

echo; echo "Clean up ..."
docker system prune -f