#!/bin/sh

# If needed, add permission to make this file executable | chmod +x start

echo; echo "If not existing, create our network ..."

if [ ! "$(docker network ls --filter name=ntw_front -q)" ];then
  docker network create --driver overlay --subnet 10.11.10.0/24 --opt encrypted ntw_front
  sleep 2
fi

echo; echo "Show network..."
docker network ls | grep "ntw_"

#
# Warning: the file acme.json must have chmod 600 privilege

echo; echo "Start the stacks ..."
docker stack deploy toolproxy -c toolproxy.yml
docker stack deploy toolweb -c toolweb.yml
sleep 2

echo; echo "docker stack ls ..."
docker stack ls
sleep 2

echo; echo;

MIN=1
MAX=6
for ACTION in $(seq $MIN $MAX); do
  echo "docker service ls | #$ACTION"
	docker service ls && echo && sleep 2;
done

echo; echo "docker service logs -f proxy_traefik ..."
docker service logs -f toolproxy_traefik