#!/bin/sh

MAIN_URL="http://cloudwait.com"
WEBAPP=(a-gix b-gix a-cad b-cad a-who b-who a-der b-der)
#
NUMBER=100
CONCURRENT=5
IMG_ab="devmtl/ab-fire:2.3-0"

for ACTION in "${WEBAPP[@]}"; do
	echo
  echo "$MAIN_URL/$ACTION" | grep $ACTION
  
  #Confirm the page is responding
	curl -Is --head $MAIN_URL/$ACTION | grep -F -o "HTTP/1.1 200 OK"

  #Show page content
  curl -v $MAIN_URL/$ACTION

  #Show page responsiveness average
  docker run --rm "$IMG_ab" \
    ab -k -n "$NUMBER" -c "$CONCURRENT" "$MAIN_URL/$ACTION" | tail -5 | head -3
done