defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$$2y$$05$$F44r3C0UXd5aK/o6Y7KgwObpYXJzUMe/rAfP2q9fxiw1DZfUEdl1S"]
  [entryPoints.http]
    address = ":80"
#      [entryPoints.http.redirect]
#        entryPoint = "https"
#  [entryPoints.https]
#    address = ":443"
#      [entryPoints.https.tls]

[api]
entrypoint="dashboard"

#[acme]
#email = "your_email@your_domain.net"
#storage = "acme.json"
#entryPoint = "https"
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
#onHostRule = true
#  [acme.httpChallenge]
#  entryPoint = "http"
