#!/bin/sh

# Add permission to make this file executable | chmod +x start

echo; echo "create our two networks ..."

docker network create --driver overlay --subnet 10.11.10.0/24 --opt encrypted ntw_front
docker network create --driver overlay --subnet 10.12.10.0/24 --opt encrypted ntw_socketproxy
docker network ls | grep "ntw_"

sleep 2
echo; echo "start service socketproxy ..."
docker service create \
--name tool-socketproxy \
--network ntw_socketproxy \
--replicas 1 \
--mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
--constraint 'node.role==manager' \
-e CONTAINERS=1 \
-e NETWORKS=1 \
-e SERVICES=1 \
-e SWARM=1 \
-e TASKS=1 \
tecnativa/docker-socket-proxy

sleep 2
echo; echo "start service traefik ..."
docker service create \
--name tool-traefik \
--network ntw_front \
--network ntw_socketproxy \
--mode global \
-p 80:80 \
-p 443:443 \
-p 8080:8080 \
--constraint 'node.role==worker' \
traefik:1.2.3-alpine \
--docker \
--docker.swarmmode \
--docker.endpoint=tcp://tool-socketproxy:2375 \
--web

echo; echo "start the webapps services ..."
docker stack deploy webapp -c webapps.yml

echo; echo "docker stack ls ..."
sleep 2
docker stack ls

echo; echo "docker service ls ..."
sleep 2
docker service ls