#!/usr/bin/env bash

###############################################################################
# Bash best practice
###############################################################################

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Print a helpful message if a pipeline with non-zero exit code causes the
# script to exit as described above.
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR

# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset


###############################################################################
# Functions
###############################################################################

docker run --rm -ti \
  --name=ctop \
  -v /var/run/docker.sock:/var/run/docker.sock \
  quay.io/vektorlab/ctop:latest

#
# by Pascal Andy 2017-09-20_21h37
# https://twitter.com/askpascalandy
# https://github.com/pascalandy/docker-stack-this
#