#!/usr/bin/env bash

###############################################################################
# Bash best practice
###############################################################################

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Print a helpful message if a pipeline with non-zero exit code causes the
# script to exit as described above.
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR

# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset

# If needed, add permission to make this file executable | chmod +x start
# Warning: the file acme.json must have chmod 600 privilege


###############################################################################
# Functions
###############################################################################

echo; echo "Remove stacks ..."
docker stack rm toolproxy || true; sleep 1;

docker stack rm toolweb || true; sleep 1;

docker stack rm toolwordpress || true; sleep 1;

docker stack rm toolportainer || true; sleep 1;

#echo; echo "Remove network ..."
#docker network rm ntw_front

#echo; echo "Clean up ..."
#docker system prune -f