#!/usr/bin/env bash

###############################################################################
# Bash best practice
###############################################################################

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o nounset

###############################################################################
# Functions
###############################################################################

# wip https://github.com/elastic/examples/tree/master/Miscellaneous/docker/full_stack_example

# Stop
echo; echo "If existing, remove stacks: "
#./run

# Create Network
echo; echo "If not existing, create our network: "

if [ ! "$(docker network ls --filter name=ntw_front -q)" ];then
  docker network create --driver overlay --subnet 10.11.10.0/24 --opt encrypted ntw_front
  sleep 2
fi

if [ ! "$(docker network ls --filter name=ntw_back -q)" ];then
  docker network create --driver overlay --subnet 10.12.10.0/24 --opt encrypted ntw_back
  sleep 2
fi

# see existing network
echo; echo "Show network..."
docker network ls | grep "ntw_"
echo; echo; sleep 2

# The Stack
echo "Start the stacks ..."; echo; echo;
cd /root/docker-stack-this/traefik-manager-noacme/monorepo-elastic

# elastic stack
docker-compose -f docker-compose-linux.yml up
echo; echo;

# List
echo; echo "docker stack ls ..."
docker stack ls;
echo; echo ; sleep 2

# Follow deployment in real time
watch docker service ls
echo; echo;

# by Pascal Andy | # https://twitter.com/askpascalandy
# https://github.com/pascalandy/docker-stack-this
#